currency:
  items:
    - { code: 'USD', precision: 2, description: 'United States Dollar'}
    - { code: 'EUR', precision: 2, description: 'Euro'}
    - { code: 'UAH', precision: 2, description: 'Ukrainian Hryvna' }

